name: Health app E2E Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '24'

    - name: Install healthapp dependencies
      working-directory: healthapp
      run: npm install

    - name: Install test dependencies
      working-directory: tests
      run: npm install

    - name: Run E2E tests
      working-directory: tests
      run: npm test